# Generated by Django 4.1.2 on 2022-11-17 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_klass_user_alter_klass_end_recursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='user',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
