# Generated by Django 4.1.2 on 2022-11-17 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_alter_klass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='klass',
            name='next_klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.klass'),
        ),
        migrations.AddField(
            model_name='klass',
            name='week',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='klass',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='klass',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
