# Generated by Django 4.1.2 on 2022-11-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_klass_date_klass_next_klass_klass_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='next_klass',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.klass'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='user',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klass',
            name='week',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
