# Generated by Django 4.1.2 on 2022-11-17 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_alter_klass_date_alter_klass_next_klass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='user',
            field=models.ManyToManyField(default=None, editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
