# Generated by Django 4.1.2 on 2022-11-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_klass_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'ordering': ['date'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
