# Generated by Django 4.1.2 on 2022-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_klass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='start_day',
            field=models.DateField(null=True, verbose_name='First day of classes'),
        ),
    ]
