# Generated by Django 4.1.2 on 2022-11-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_klass_start_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='start_day',
            new_name='first_day',
        ),
    ]
