# Generated by Django 4.1.2 on 2022-11-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_rename_start_day_klass_first_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='week',
        ),
    ]
