# Generated by Django 4.1.2 on 2022-11-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_studio_phone_num'),
        ('classes', '0010_remove_klass_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='klass',
            unique_together={('name', 'studio', 'day', 'start_time', 'end_time')},
        ),
    ]
