# Generated by Django 4.1.2 on 2022-11-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_klass_unique_together_klass_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='klass',
            name='constraint',
        ),
    ]
