# Generated by Django 4.1.2 on 2022-12-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_klass_next_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='next_klass',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.klass'),
        ),
    ]
