# Generated by Django 4.1.2 on 2022-11-18 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_plan',
            new_name='current_subscription',
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_period',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_info',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Not a valid Phone numer', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
