# Generated by Django 4.1.2 on 2022-11-17 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_name_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='phone_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Invalid phone number')]),
        ),
    ]
